"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubUnit = exports.Unit = exports.SchoolOrOffice = exports.EmployeePosition = exports.WorkflowInstanceStage = exports.WorkflowRequest = exports.Stage = exports.Workflow = exports.Employee = exports.Position = exports.Department = exports.Organization = void 0;
require("reflect-metadata");
const Organization_1 = require("./Organization");
Object.defineProperty(exports, "Organization", { enumerable: true, get: function () { return Organization_1.Organization; } });
const Department_1 = require("./Department");
Object.defineProperty(exports, "Department", { enumerable: true, get: function () { return Department_1.Department; } });
const Position_1 = require("./Position");
Object.defineProperty(exports, "Position", { enumerable: true, get: function () { return Position_1.Position; } });
const Employee_1 = require("./Employee");
Object.defineProperty(exports, "Employee", { enumerable: true, get: function () { return Employee_1.Employee; } });
const Workflow_1 = require("./Workflow");
Object.defineProperty(exports, "Workflow", { enumerable: true, get: function () { return Workflow_1.Workflow; } });
const Stage_1 = require("./Stage");
Object.defineProperty(exports, "Stage", { enumerable: true, get: function () { return Stage_1.Stage; } });
const WorkflowRequest_1 = require("./WorkflowRequest");
Object.defineProperty(exports, "WorkflowRequest", { enumerable: true, get: function () { return WorkflowRequest_1.WorkflowRequest; } });
const WorkflowInstanceStage_1 = require("./WorkflowInstanceStage");
Object.defineProperty(exports, "WorkflowInstanceStage", { enumerable: true, get: function () { return WorkflowInstanceStage_1.WorkflowInstanceStage; } });
const EmployeePosition_1 = require("./EmployeePosition");
Object.defineProperty(exports, "EmployeePosition", { enumerable: true, get: function () { return EmployeePosition_1.EmployeePosition; } });
const SchoolOrOffice_1 = require("./SchoolOrOffice");
Object.defineProperty(exports, "SchoolOrOffice", { enumerable: true, get: function () { return SchoolOrOffice_1.SchoolOrOffice; } });
const Unit_1 = require("./Unit");
Object.defineProperty(exports, "Unit", { enumerable: true, get: function () { return Unit_1.Unit; } });
const SubUnit_1 = require("./SubUnit");
Object.defineProperty(exports, "SubUnit", { enumerable: true, get: function () { return SubUnit_1.SubUnit; } });
//# sourceMappingURL=index.js.map